# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-08 08:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
        ('traders', '0001_initial'),
        ('trading_accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trader',
            name='selected_trading_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='trading_accounts.TradingAccount'),
        ),
        migrations.AddField(
            model_name='trader',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
