language: python
python:
  - "3.5"
env:
  - DJANGO=1.11 DB=postgres

services:
  - postgresql

branches:
  only:
    - master
    - develop

intall:
  - pip install -r requirements.txt

before_script:
  - psql -c "CREATE DATABASE ${DATABASE_NAME};" -U postgres
  - psql -c "CREATE USER ${DATABASE_USER} WITH PASSWORD '${DATABASE_PASSWORD}';" -U postgres
  - psql -c "ALTER USER ${DATABASE_USER} CREATEDB;" -U postgres
  - psql -c "GRANT ALL PRIVILEGES ON DATABASE ${DATABASE_NAME} TO ${DATABASE_USER};" -U postgres

script:
  - python manage.py test