# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 07:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(choices=[('EURUSD', 'Euro vs US Dollar'), ('GBPUSD', 'Great Britain vs US Dollar'), ('USDJPY', 'US Dollar vs Japanese Yen'), ('USDCHF', 'US Dollar vs Swiss Franc')], max_length=6)),
                ('bid_price', models.DecimalField(decimal_places=4, max_digits=10)),
                ('ask_price', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
